### ISSUE TITLE
Release to support 8.8.1

### ISSUE THREAD

**Issue by domenkozar** [haskell-hvr/regex-posix#3]

**Comment by psibi** [comment]
I would also love to see a new release. This affects xmonad-extras currently: https://github.com/xmonad/xmonad-extras/issues/24

**Comment by asr** [comment]
Also blocking https://github.com/agda/agda/issues/3725.

**Comment by hvr** [comment]
resolved by https://hackage.haskell.org/package/regex-posix-0.96.0.0

See also https://matrix.hackage.haskell.org/package/regex-posix
